// Authentification
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Locations
// Users
export const LOAD_LOCATIONS = "LOAD_LOCATIONS";
export const LOAD_LOCATIONS_SUCCESS = "LOAD_LOCATIONS_SUCCESS";
export const LOAD_LOCATIONS_ERROR = "LOAD_LOCATIONS_ERROR";

export const LOAD_LOCATION = "LOAD_LOCATION";
export const LOAD_LOCATION_SUCCESS = "LOAD_LOCATION_SUCCESS";
export const LOAD_LOCATION_ERROR = "LOAD_LOCATION_ERROR";

export const VALIDATE_LOCATION = "VALIDATE_LOCATION";
export const VALIDATE_LOCATION_ERROR = "VALIDATE_LOCATION_ERROR";

export const DEACTIVATE_LOCATION = "DEACTIVATE_LOCATION";
export const DEACTIVATE_LOCATION_ERROR = "DEACTIVATE_LOCATION_ERROR";

// Users
export const LOAD_USERS = "LOAD_USERS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

export const ACTIVATE_USER = "ACTIVATE_USER";
export const ACTIVATE_USER_ERROR = "ACTIVATE_USER_ERROR";

export const DEACTIVATE_USER = "DEACTIVATE_USER";
export const DEACTIVATE_USER_ERROR = "DEACTIVATE_USER_ERROR";

// Manage comments
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_ERROR = "LOAD_COMMENTS_ERROR";

export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

// destinations
export const LOAD_DESTINATIONS = "LOAD_DESTINATIONS";
export const LOAD_DESTINATIONS_SUCCESS = "LOAD_DESTINATIONS_SUCCESS";
export const LOAD_DESTINATIONS_ERROR = "LOAD_DESTINATIONS_ERROR";

export const ADD_DESTINATION = "ADD_DESTINATION";
export const ADD_DESTINATION_ERROR = "ADD_DESTINATION_ERROR";

// Thématiques
export const LOAD_THEMATICS = "LOAD_THEMATICS";
export const LOAD_THEMATICS_SUCCESS = "LOAD_THEMATICS_SUCCESS";
export const LOAD_THEMATICS_ERROR = "LOAD_THEMATICS_ERROR";

export const ADD_THEMATIC = "ADD_THEMATIC";
export const ADD_THEMATIC_ERROR = "ADD_THEMATIC_ERROR";

// Categories
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_ERROR = "LOAD_CATEGORIES_ERROR";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";

// Paramétres
export const LOAD_FIELDS = "LOAD_FIELDS";
export const LOAD_FIELDS_ERROR = "LOAD_FIELDS_ERROR";

export const ADD_FIELD = "ADD_FIELD";
export const ADD_FIELD_ERROR = "ADD_FIELD_ERROR";
