//User
export const AUTH_ERRO = "AUTH_ERRO";
export const AUTH_USER = "AUTH_USER";
export const REG_USER = "REG_USER";
export const REG_ERRO = "REG_ERRO";
export const GET_USER = "GET_USER";

//Owner
export const REG_OWN = "REG_OWN";
export const REG_OWN_ERROR = "REG_OWN_ERROR";

// Thematics
export const LOAD_THEMATICS = "LOAD_THEMATICS";
export const LOAD_THEMATICS_SUCCESS = "LOAD_THEMATICS_SUCCESS";
export const LOAD_THEMATICS_ERROR = "LOAD_THEMATICS_ERROR";

// Locations
export const LOAD_LOCATIONS = "LOAD_LOCATIONS";
export const LOAD_LOCATIONS_SUCCESS = "LOAD_LOCATIONS_SUCCESS";
export const LOAD_LOCATIONS_ERROR = "LOAD_LOCATIONS_ERROR";

//Load location
export const LOAD_ALL_LOCATIONS = " LOAD_ALL_LOCATIONS";
export const LOAD_LOCATION = "LOAD_LOCATION";
export const LOAD_LOCATION_SUCCESS = "LOAD_LOCATION_SUCCESS";
export const LOAD_LOCATION_ERROR = "LOAD_LOCATION_ERROR";

//Add location
export const ADD_LOCATION = "ADD_LOCATION";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_ERROR = "ADD_LOCATION_ERROR";

// Categories
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_ERROR = "LOAD_CATEGORIES_ERROR";
// Locations
// export const LOAD_LOCATIONS = "LOAD_LOCATIONS";
// export const LOAD_LOCATIONS_ERROR = "LOAD_LOCATIONS_ERROR";

// Destinations

export const GET_ALL_DESTINATIONS = "GET_ALL_DESTINATIONS";
export const LOAD_DESTINATIONS = "LOAD_DESTINATIONS";
export const LOAD_DESTINATIONS_SUCCESS = "LOAD_DESTINATIONS_SUCCESS";
export const LOAD_DESTINATIONS_ERROR = "LOAD_DESTINATIONS_ERROR";

// Fields
export const LOAD_FIELDS = "LOAD_FIELDS";
export const LOAD_FIELDS_SUCCESS = "LOAD_FIELDS_SUCCESS";
export const LOAD_FIELDS_ERROR = "LOAD_FIELDS_ERROR";

//Add Booking
export const ADD_BOOKING = "ADD_BOOKING";
export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS";
export const ADD_BOOKING_ERROR = "ADD_BOOKING_ERROR";

//Load busy date slots
export const LOAD_DATE_SLOTS = "LOAD_DATE_SLOTS";
export const LOAD_DATE_SLOTS_SUCCESS = "LOAD_DATE_SLOTS_SUCCESS";
export const LOAD_DATE_SLOTS_ERROR = "LOAD_DATE_SLOTS_ERROR";

//Load user's bookings
export const LOAD_USER_BOOKINGS = "LOAD_USER_BOOKINGS";
export const LOAD_USER_BOOKING_SUCCESS = "LOAD_USER_BOOKING_SUCCESS";
export const LOAD_USER_BOOKINGS_ERROR = "LOAD_USER_BOOKINGS_ERROR";

// Load owner's bookings
export const LOAD_OWNER_BOOKINGS = "LOAD_OWNER_BOOKINGS";
export const LOAD_OWNER_BOOKING_SUCCESS = "LOAD_OWNER_BOOKING_SUCCESS";
export const LOAD_OWNER_BOOKINGS_ERROR = "LOAD_OWNER_BOOKINGS_ERROR";

//Update booking status
export const UPDATE_BOOKING_STATUS = "UPDATE_BOOKING_STATUS";
export const UPDATE_BOOKING_STATUS_SUCCESS = "UPDATE_BOOKING_STATUS_SUCCESS";
export const UPDATE_BOOKING_STATUS_ERROR = "UPDATE_BOOKING_STATUS_ERROR";

//Update user profile
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

// Comment and user's reviews

//Reviews
export const LOAD_REVIEWS = "LOAD_REVIEWS";
export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS";
export const LOAD_REVIEWS_ERROR = "LOAD_REVIEWS_ERROR";

//Add review
export const ADD_REVIEW = "ADD_REVIEW";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_ERROR = "ADD_REVIEW_ERROR";

// Comments
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_ERROR = "LOAD_COMMENTS_ERROR";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

//Activities
export const LOAD_ACTIVITIES = "LOAD_ACTIVITIES";
export const LOAD_ACTIVITIES_SUCCESS = "LOAD_ACTIVITIES_SUCCESS";
export const LOAD_ACTIVITIES_ERROR = "LOAD_ACTIVITIES_ERROR";

export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const ADD_ACTIVITY_SUCCESS = "ADD_ACTIVITY_SUCCESS";
export const ADD_ACTIVITY_ERROR = "ADD_ACTIVITY_ERROR";
//Loadind

export const LOAD_END = "LOAD_END";
