api_platform:
    resource: .
    type: api_platform
    prefix: /api/v01
app_swagger_ui:
    path: /api/At181094/documentation
    methods: GET
    defaults: { _controller: api_platform.swagger.action.ui,area: default }

login:
    path: /login
    methods: ['POST'] 
